[package]
name = "url_shortener"
version = "0.1.0"
authors = ["Your Name"]
edition = "2021"

[dependencies]
actix-web = "4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
actix-rt = "2.0"
rusqlite = "0.29.0"
