[package]
name = "hypercache"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"  # For time-based eviction
tokio = { version = "1", features = ["full"] }  # For async runtime (optional)
