[package]
name = "web3_backend"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = "0.3"
ethers = { version = "1", features = ["blocking", "async-std"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
